### ISSUE TITLE
Run uc-agent-flow Error

### ISSUE THREAD

**Issue by GertjanAntonisse** [Synestheticminds/UnderdogCowboy#10]
After run pip uninstall underdogcowboy and run pup install underdogcowboy and try to run uc-agent-flow this error occured.

C:\Windows\System32>uc-agent-flow
Pre Release -- Early Access Version... Nov-Dec 2024
If you do not have my Whatsapp, DM on linked-in for issues that need solving: https://www.linkedin.com/in/reneluijk/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Office C2C\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\uc-agent-flow.exe\__main__.py", line 4, in <module>
  File "C:\Users\Office C2C\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\underdogcowboy\__init__.py", line 80, in <module>
    from .core.uc_agent_communicator import UCAgentCommunicator
  File "C:\Users\Office C2C\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\underdogcowboy\core\uc_agent_communicator.py", line 56, in <module>
    from uccli import AgentCommunicator
  File "C:\Users\Office C2C\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\uccli\__init__.py", line 1, in <module>
    from .main import (
  File "C:\Users\Office C2C\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\uccli\main.py", line 32, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'

**Comment by rluijk** [comment]
This is most likely resolved with the newly released version of the uccli library.

Local test result on the whl file shows all packages the uccli library depends on are installed when running a pip install.

This fix will be integrated in the 0.1.14.3 release of UC

<img width="1467" alt="Screenshot 2024-11-26 at 08 09 18" src="https://github.com/user-attachments/assets/a4c88b3f-c86c-403f-b93e-0fb384cfa263">
